version: "3.7"
services:
  wpaudit:
    image: wpaudit:latest
    env_file:
      - config/build.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VCS_REF
        - VCS_URL
        - VERSION
        - BUILD_DATE
        - VENDOR
        - NAME
        - DESCRIPTION
